number = input ("Enter number")
number_two = input("Enter another number")
print("Printing type of input value")
print ("type of number ", type(number))
print ("type of number_two ", type(number_two ))